# Generated by Django 6.0.6 on 2026-06-26 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilJoueur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(blank=True, choices=[('meneur', 'Meneur'), ('arriere', 'Arrière'), ('ailier', 'Ailier'), ('ailier_fort', 'Ailier Fort'), ('pivot', 'Pivot')], db_index=True, max_length=20)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('taille', models.PositiveSmallIntegerField(blank=True, help_text='en cm', null=True)),
                ('bio', models.TextField(blank=True)),
                ('tournois_joues', models.PositiveIntegerField(default=0)),
                ('tournois_gagnes', models.PositiveIntegerField(default=0)),
                ('mvp_count', models.PositiveIntegerField(default=0)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_joueur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil joueur',
                'verbose_name_plural': 'Profils joueurs',
            },
        ),
    ]
