# Generated by Django 6.0.6 on 2026-07-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiljoueur',
            name='grade',
            field=models.CharField(choices=[('bronze', 'Bronze'), ('argent', 'Argent'), ('or', 'Or'), ('platine', 'Platine'), ('legende', 'Légende')], db_index=True, default='bronze', max_length=10),
        ),
        migrations.AddField(
            model_name='profiljoueur',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
