# Generated by Django 6.0.6 on 2026-07-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_profiljoueur_grade_profiljoueur_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiljoueur',
            name='sport',
            field=models.CharField(choices=[('basket', 'Basketball'), ('football', 'Football')], db_index=True, default='basket', max_length=10),
        ),
        migrations.AlterField(
            model_name='profiljoueur',
            name='poste',
            field=models.CharField(blank=True, choices=[('meneur', 'Meneur'), ('arriere', 'Arrière'), ('ailier', 'Ailier'), ('ailier_fort', 'Ailier Fort'), ('pivot', 'Pivot'), ('gardien', 'Gardien'), ('defenseur', 'Défenseur'), ('milieu', 'Milieu'), ('attaquant', 'Attaquant')], db_index=True, max_length=20),
        ),
    ]
