# Generated by Django 6.0.6 on 2026-07-09 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('type_evenement', models.CharField(choices=[('exhibition', 'Match exhibition'), ('camp', "Camp d'entraînement"), ('dunk_contest', 'Concours de dunks / shoots'), ('animation', 'Animation / Show'), ('caritatif', 'Événement caritatif'), ('autre', 'Autre')], db_index=True, max_length=20)),
                ('commune', models.CharField(db_index=True, max_length=100)),
                ('lieu', models.CharField(max_length=200)),
                ('date_debut', models.DateField(db_index=True)),
                ('date_fin', models.DateField()),
                ('heure', models.TimeField(blank=True, null=True)),
                ('prix_entree', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('affiche', models.ImageField(blank=True, null=True, upload_to='evenements/affiches/')),
                ('statut', models.CharField(choices=[('a_venir', 'À venir'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], db_index=True, default='a_venir', max_length=20)),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisateur', models.ForeignKey(limit_choices_to={'role__in': ['organisateur', 'promoteur']}, on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='InteretEvenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interesses', to='events.evenement')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interets_evenements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Intérêt événement',
            },
        ),
        migrations.AddIndex(
            model_name='evenement',
            index=models.Index(fields=['commune', 'date_debut', 'statut'], name='events_even_commune_6932d7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='interetevenement',
            unique_together={('utilisateur', 'evenement')},
        ),
    ]
