# Generated by Django 6.0.6 on 2026-07-10 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='organisateur',
            field=models.ForeignKey(limit_choices_to={'role': 'promoteur'}, on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to=settings.AUTH_USER_MODEL),
        ),
    ]
