# Generated by Django 6.0.6 on 2026-07-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_evenement_organisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='sport',
            field=models.CharField(choices=[('basket', 'Basketball'), ('football', 'Football')], db_index=True, default='basket', max_length=10),
        ),
    ]
