# Generated by Django 6.0.6 on 2026-07-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('organisateur', 'Organisateur'), ('promoteur', 'Promoteur'), ('joueur', 'Joueur'), ('client', 'Client / Recruteur')], max_length=20),
        ),
    ]
