# Generated by Django 6.0.6 on 2026-07-10 22:49

from django.db import migrations, models


def organisateurs_vers_promoteurs(apps, schema_editor):
    """Fusion des rôles : tous les anciens organisateurs deviennent promoteurs."""
    Utilisateur = apps.get_model('accounts', 'Utilisateur')
    Utilisateur.objects.filter(role='organisateur').update(role='promoteur')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_utilisateur_role'),
    ]

    operations = [
        migrations.RunPython(organisateurs_vers_promoteurs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('promoteur', 'Promoteur'), ('joueur', 'Joueur'), ('client', 'Client / Recruteur')], max_length=20),
        ),
    ]
