# Generated by Django 6.0.6 on 2026-06-26 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Équipe',
            },
        ),
        migrations.CreateModel(
            name='Tournoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('commune', models.CharField(db_index=True, max_length=100)),
                ('lieu', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('date_debut', models.DateField(db_index=True)),
                ('date_fin', models.DateField()),
                ('format', models.CharField(choices=[('3x3', '3x3'), ('5x5', '5x5')], db_index=True, max_length=10)),
                ('niveau', models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('elite', 'Élite')], max_length=20)),
                ('frais_inscription', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('affiche', models.ImageField(blank=True, null=True, upload_to='tournois/affiches/')),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('complet', 'Complet'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], db_index=True, default='ouvert', max_length=20)),
                ('nombre_equipes_max', models.PositiveIntegerField(blank=True, null=True)),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisateur', models.ForeignKey(limit_choices_to={'role': 'organisateur'}, on_delete=django.db.models.deletion.CASCADE, related_name='tournois', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tournoi',
                'verbose_name_plural': 'Tournois',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipe_gagnante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='victoires', to='tournaments.equipe')),
                ('mvp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mvps', to=settings.AUTH_USER_MODEL)),
                ('saisi_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultats_saisis', to=settings.AUTH_USER_MODEL)),
                ('tournoi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultat', to='tournaments.tournoi')),
            ],
            options={
                'verbose_name': 'Résultat',
            },
        ),
        migrations.CreateModel(
            name='FavoriTournoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris_tournois', to=settings.AUTH_USER_MODEL)),
                ('tournoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favori_par', to='tournaments.tournoi')),
            ],
            options={
                'verbose_name': 'Favori',
            },
        ),
        migrations.AddField(
            model_name='equipe',
            name='tournoi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipes', to='tournaments.tournoi'),
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='tournaments.equipe')),
                ('joueur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Participation',
                'unique_together': {('joueur', 'equipe')},
            },
        ),
        migrations.AddIndex(
            model_name='tournoi',
            index=models.Index(fields=['commune', 'date_debut', 'statut'], name='tournaments_commune_8e32ca_idx'),
        ),
        migrations.AddIndex(
            model_name='tournoi',
            index=models.Index(fields=['format', 'niveau'], name='tournaments_format_4cd8d2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favoritournoi',
            unique_together={('utilisateur', 'tournoi')},
        ),
        migrations.AlterUniqueTogether(
            name='equipe',
            unique_together={('tournoi', 'nom')},
        ),
    ]
