# Generated by Django 6.0.6 on 2026-07-09 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tournoi',
            name='mis_en_avant',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='tournoi',
            name='organisateur',
            field=models.ForeignKey(limit_choices_to={'role__in': ['organisateur', 'promoteur']}, on_delete=django.db.models.deletion.CASCADE, related_name='tournois', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tournoi',
            name='statut',
            field=models.CharField(choices=[('en_attente_paiement', 'En attente de paiement'), ('ouvert', 'Ouvert'), ('complet', 'Complet'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], db_index=True, default='ouvert', max_length=20),
        ),
    ]
