# Generated by Django 6.0.6 on 2026-07-09 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_tournoi_mis_en_avant_alter_tournoi_organisateur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultat',
            name='equipe_finaliste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finales_perdues', to='tournaments.equipe'),
        ),
        migrations.AddField(
            model_name='resultat',
            name='score_finaliste',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultat',
            name='score_gagnante',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
