# Generated by Django 6.0.6 on 2026-07-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_resultat_equipe_finaliste_resultat_score_finaliste_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournoi',
            name='statut',
            field=models.CharField(choices=[('ouvert', 'Ouvert'), ('complet', 'Complet'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], db_index=True, default='ouvert', max_length=20),
        ),
    ]
