# Generated by Django 6.0.6 on 2026-07-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_alter_tournoi_organisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournoi',
            name='sport',
            field=models.CharField(choices=[('basket', 'Basketball'), ('football', 'Football')], db_index=True, default='basket', max_length=10),
        ),
        migrations.AlterField(
            model_name='tournoi',
            name='format',
            field=models.CharField(choices=[('3x3', '3x3'), ('5x5', '5x5'), ('maracana', 'Maracana'), ('7x7', '7 vs 7'), ('11x11', '11 vs 11')], db_index=True, max_length=10),
        ),
    ]
