# Generated by Django 6.0.6 on 2026-07-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_tournoi_sport_alter_tournoi_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournoi',
            name='statut',
            field=models.CharField(choices=[('en_attente_paiement', 'En attente de paiement'), ('ouvert', 'Ouvert'), ('complet', 'Complet'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], db_index=True, default='ouvert', max_length=20),
        ),
    ]
