# Generated by Django 6.0.6 on 2026-07-14 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_alter_tournoi_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='payee',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
