# Generated by Django 6.0.6 on 2026-07-14 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_equipe_payee'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='mise_en_avant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournoi',
            name='categorie_age',
            field=models.CharField(choices=[('open', 'Toutes catégories'), ('u15', 'U15 — moins de 15 ans'), ('u18', 'U18 — moins de 18 ans'), ('u21', 'U21 — moins de 21 ans'), ('senior', 'Seniors — 18 ans et plus'), ('veteran35', 'Vétérans — 35 ans et plus')], db_index=True, default='open', max_length=12),
        ),
    ]
