# Generated by Django 6.0.6 on 2026-06-26 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarteTransfert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponible', models.BooleanField(db_index=True, default=True)),
                ('description', models.TextField(blank=True, help_text='Ce que le joueur recherche')),
                ('pretentions', models.TextField(blank=True, help_text='Niveau souhaité, zone géographique, etc.')),
                ('mise_en_avant', models.BooleanField(db_index=True, default=False)),
                ('mise_en_avant_jusqu', models.DateTimeField(blank=True, null=True)),
                ('badge_verifie', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('joueur', models.OneToOneField(limit_choices_to={'role': 'joueur'}, on_delete=django.db.models.deletion.CASCADE, related_name='carte_transfert', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carte de transfert',
                'verbose_name_plural': 'Cartes de transfert',
                'ordering': ['-mise_en_avant', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée')], db_index=True, default='en_attente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emetteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres_envoyees', to=settings.AUTH_USER_MODEL)),
                ('joueur', models.ForeignKey(limit_choices_to={'role': 'joueur'}, on_delete=django.db.models.deletion.CASCADE, related_name='offres_recues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Offre',
                'verbose_name_plural': 'Offres',
                'ordering': ['-created_at'],
            },
        ),
    ]
