# Generated by Django 6.0.6 on 2026-07-09 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RechercheRecruteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(blank=True, max_length=20)),
                ('commune', models.CharField(blank=True, max_length=100)),
                ('grade', models.CharField(blank=True, max_length=10)),
                ('texte', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recherches_recruteur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recherche recruteur',
                'verbose_name_plural': 'Recherches recruteurs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['utilisateur', '-created_at'], name='market_rech_utilisa_e05ac4_idx')],
            },
        ),
    ]
