# Generated by Django 6.0.6 on 2026-07-09 13:09

import apps.payments.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournaments', '0002_tournoi_mis_en_avant_alter_tournoi_organisateur_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_paiement', models.CharField(choices=[('publication_tournoi', 'Publication de tournoi promu')], max_length=30)),
                ('montant', models.DecimalField(decimal_places=0, max_digits=10)),
                ('devise', models.CharField(default='XOF', max_length=5)),
                ('reference', models.CharField(default=apps.payments.models.generer_reference, max_length=40, unique=True)),
                ('genius_reference', models.CharField(blank=True, db_index=True, max_length=60)),
                ('checkout_url', models.URLField(blank=True, max_length=500)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('reussi', 'Réussi'), ('echoue', 'Échoué'), ('annule', 'Annulé'), ('expire', 'Expiré')], db_index=True, default='en_attente', max_length=20)),
                ('simulation', models.BooleanField(default=False)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tournoi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='tournaments.tournoi')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-created_at'],
            },
        ),
    ]
