# Generated by Django 6.0.6 on 2026-07-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='type_paiement',
            field=models.CharField(choices=[('publication_tournoi', 'Promotion de tournoi')], max_length=30),
        ),
    ]
