# Generated by Django 6.0.6 on 2026-07-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_paiement_type_paiement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='type_paiement',
            field=models.CharField(choices=[('publication_tournoi', 'Promotion de tournoi'), ('creation_tournoi', 'Publication de tournoi')], max_length=30),
        ),
    ]
