# Generated by Django 6.0.6 on 2026-07-14 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_paiement_type_paiement'),
        ('tournaments', '0008_equipe_payee'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='equipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='tournaments.equipe'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='type_paiement',
            field=models.CharField(choices=[('publication_tournoi', 'Promotion de tournoi'), ('creation_tournoi', 'Publication de tournoi'), ('inscription_equipe', "Inscription d'équipe")], max_length=30),
        ),
    ]
