# Generated by Django 6.0.6 on 2026-07-14 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_paiement_equipe_alter_paiement_type_paiement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='type_paiement',
            field=models.CharField(choices=[('publication_tournoi', 'Promotion de tournoi'), ('creation_tournoi', 'Publication de tournoi'), ('inscription_equipe', "Inscription d'équipe"), ('promotion_compte', 'Promotion de compte joueur'), ('promotion_equipe', "Promotion d'équipe")], max_length=30),
        ),
    ]
