# Generated by Django 6.0.6 on 2026-07-14 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_paiement_type_paiement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portefeuille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('total_credite', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('total_reverse', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('promoteur', models.OneToOneField(limit_choices_to={'role': 'promoteur'}, on_delete=django.db.models.deletion.CASCADE, related_name='portefeuille', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portefeuille',
            },
        ),
        migrations.CreateModel(
            name='MouvementPortefeuille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('credit_inscription', "Crédit d'inscription"), ('reversement', 'Reversement')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12)),
                ('libelle', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paiement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements', to='payments.paiement')),
                ('portefeuille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='payments.portefeuille')),
            ],
            options={
                'verbose_name': 'Mouvement de portefeuille',
                'verbose_name_plural': 'Mouvements de portefeuille',
                'ordering': ['-created_at'],
            },
        ),
    ]
