# Generated by Django 6.0.6 on 2026-07-14 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_portefeuille_mouvementportefeuille'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeRetrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12)),
                ('numero', models.CharField(help_text='Numéro Mobile Money du promoteur', max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('traite', 'Traité'), ('rejete', 'Rejeté')], db_index=True, default='en_attente', max_length=20)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('traite_at', models.DateTimeField(blank=True, null=True)),
                ('portefeuille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_retrait', to='payments.portefeuille')),
            ],
            options={
                'verbose_name': 'Demande de retrait',
                'verbose_name_plural': 'Demandes de retrait',
                'ordering': ['-created_at'],
            },
        ),
    ]
